import { z } from 'zod';

const configSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  DATABASE_URL: z.string().min(1),
  /** 32+ character key used for AES-256-GCM PAT encryption */
  ENCRYPTION_KEY: z.string().min(32),
  LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
  /** Opaque session secret for workspace auth (Next.js web only) */
  SESSION_SECRET: z.string().min(32).optional(),
  PORT: z.coerce.number().int().positive().default(3000),
  /** 5–15 minute default sync interval guard — scopes override this per board */
  DEFAULT_SYNC_INTERVAL_MINUTES: z.coerce.number().int().min(5).max(15).default(10),
});

export type Config = z.infer<typeof configSchema>;

let _config: Config | undefined;

/**
 * Resolve the database URL from a configurable source variable.
 *
 * Managed-service deployments often inject the PostgreSQL connection string
 * under an autogenerated variable name (e.g. `XYZ_POSTGRESQL_URI`) that the
 * application cannot rename. Setting `DATABASE_URL_ENV_VAR` to that name lets
 * shared config read the connection string from there while preserving the
 * default `DATABASE_URL` behavior for local/dev/docker usage.
 *
 * Side effect: when `DATABASE_URL_ENV_VAR` is used, the resolved value is
 * written back to `process.env.DATABASE_URL` so that downstream consumers that
 * read the environment directly (notably Prisma, which resolves
 * `env("DATABASE_URL")` from the schema at client construction time) see a
 * consistent value.
 */
function resolveDatabaseUrlFromEnv(): void {
  const sourceVarName = process.env['DATABASE_URL_ENV_VAR'];
  if (sourceVarName === undefined || sourceVarName === '') {
    return;
  }

  if (sourceVarName === 'DATABASE_URL') {
    // Explicitly pointing at the default name is a no-op; fall through to the
    // standard DATABASE_URL parsing below.
    return;
  }

  const resolved = process.env[sourceVarName];
  if (resolved === undefined || resolved === '') {
    throw new Error(
      `Invalid environment configuration:\n  DATABASE_URL_ENV_VAR: points to "${sourceVarName}", but that variable is not set or is empty`,
    );
  }

  process.env['DATABASE_URL'] = resolved;
}

export function getConfig(): Config {
  if (_config) return _config;

  resolveDatabaseUrlFromEnv();

  const result = configSchema.safeParse(process.env);
  if (!result.success) {
    throw new Error(
      `Invalid environment configuration:\n${result.error.issues
        .map((i) => `  ${i.path.join('.')}: ${i.message}`)
        .join('\n')}`,
    );
  }

  _config = result.data;
  return _config;
}

/** Reset the cached config — only used in tests. */
export function resetConfig(): void {
  _config = undefined;
}
